# Generated by Django 4.0.5 on 2022-07-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingphoto',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_photos', to='listings.listing'),
        ),
    ]
